name: main
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: |
          DISPLAY=:0.0
          echo $DISPLAY
      - name: Checkout Code
        uses: actions/checkout@v3
