name: main
on:
  push:
    branches:
      - experimental_cache_restore_time

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd

      - run: |
          DISPLAY=:0.0
          echo $DISPLAY

      - name: Checkout Code
        uses: actions/checkout@v3

      - run: ls -la

      - uses: actions/cache@v3
        id: cache-readme
        with:
          key: ${{ hashFiles('README.md',
                             'README2.md') }}
          path: |
            !**
            data1/**
            data2/**
            bb/ee/**
            cc/**

      - if: ${{ steps.cache-readme.outputs.cache-hit != 'true' }}
        name: Cache Miss Operations
        continue-on-error: true
        run: |
          echo 'Cachd miss! ${{ hashFiles('README.md') }}'
          mkdir -p data1
          mkdir -p data2
          ls -la > data1/files.txt
          ls -la > data2/files.txt
          mkdir -p bb/ee
          ls -la > bb/ee/1.txt
          mkdir -p cc
          ls -la > cc/2.txt
          mkdir -p dd
          ls -la > dd/3.txt
          ls -la > 4.txt

      - if: ${{ steps.cache-readme.outputs.cache-hit == 'true' }}
        name: Cache Hit Operations
        continue-on-error: true
        run: |
          echo 'Cachd hit! ${{ hashFiles('README.md') }}'
          ls -l data1
          ls -l data2
          ls -l bb/ee
          ls -l cc

      - uses: actions/upload-artifact@v3
        with:
          path: |
            !**
            data1/**
            data2/**
            bb/ee/**
            cc/**
