name: main
on:
  push:
    branches:
      - experimental_cache_mix_file

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Cache 1
        id: cache1
        with:
          key: cache1-key
          path: |
            README3.md

      - run: ls -l
        name: After Cache 1

      - uses: actions/cache@v3
        name: Cache 2
        id: cache2
        with:
          key: cache2-key-${{ hashFiles('**/*.md') }}
          path: a.cpp

      - run: ls -l
        name: After Cache 2

      - if: ${{ steps.cache1.outputs.cache-hit != 'true' }}
        name: Cache Miss Operations
        continue-on-error: true
        run: |
          cat README.md > README3.md
          cat README2.md >> README3.md

      - run: ls -l
        name: After Run
