name: main
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: |
          DISPLAY=:0.0
          echo $DISPLAY
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: ls -la
      - uses: actions/cache@v3
        id: cache-readme
        with:
          key: ${{ hashFiles('READMD.md') }}
          path: |
            data1/**
            data2/**
      - if: ${{ steps.cache-readme.outputs.cache-hit != 'true' }}
        name: List the status of readme file
        continue-on-error: true
        run: echo 'Cachd miss! ${{ hashFiles('READMD.md') }}'
      - if: ${{ steps.cache-readme.outputs.cache-hit == 'true' }}
        name: List the status of readme file
        continue-on-error: true
        run: echo 'Cachd hit! ${{ hashFiles('READMD.md') }}'
